notmuch: Update the database and tags after moving mail to a new folder

diff --git a/scripts/notmuch/notmuch-refile b/scripts/notmuch/notmuch-refile
--- a/scripts/notmuch/notmuch-refile
+++ b/scripts/notmuch/notmuch-refile
@@ -6,28 +6,67 @@
 # Usage: notmuch-refile folder query
 #
 
+################################################################################
 set -eu
 set -o pipefail
 
-if [ "$#" -lt 2 ]; then
-  echo >&2 "ERROR: Usage: $(basename "$0") folder query"
-  exit 1
-fi
+################################################################################
+search() {
+  local output=$1
+  shift
 
-mail_root=$(notmuch config get database.path)
-maildir=
+  notmuch search \
+    --output="$output" \
+    --exclude=false "$@"
+}
 
-if [ "$1" = "INBOX" ]; then
-  maildir="$mail_root"
-else
-  maildir="$mail_root/.$1"
-fi
+################################################################################
+config() {
+  notmuch config get "$@"
+}
 
-if [ ! -d "$maildir" ]; then
-  mmkdir "$maildir"
-fi
+################################################################################
+main() {
+  if [ "$#" -lt 2 ]; then
+    echo >&2 "ERROR: Usage: $(basename "$0") folder query"
+    exit 1
+  fi
 
-shift
+  mail_root=$(config database.path)
+  maildir=
 
-notmuch search --output=files --exclude=false "$@" |
-  mrefile "$maildir"
+  if [ "$1" = "INBOX" ]; then
+    maildir="$mail_root"
+  else
+    maildir="$mail_root/.$1"
+  fi
+
+  if [ ! -d "$maildir" ]; then
+    mmkdir "$maildir"
+  fi
+
+  shift
+
+  message_ids=()
+  exclude_tags=()
+
+  readarray -t message_ids < <(search messages "$@")
+  readarray -t exclude_tags < <(config search.exclude_tags | sed 's/^/-/')
+
+  for msg in "${message_ids[@]}"; do
+    # When moving a message, remove tags that might keep it from being
+    # seen in the new folder.  I'm assuming this is safe to do since
+    # tagging messages as spam, archived, deleted, etc. causes the
+    # post-tag hook script to run, and not this one.
+    notmuch tag "${exclude_tags[@]}" -- "$msg"
+
+    # Actually move the message:
+    search files "$msg" | mrefile "$maildir"
+  done
+
+  # Update the database:
+  notmuch new
+}
+
+################################################################################
+main "$@"
